### PR TITLE
feat: sync 8.23.0 and 8.23.1

### PR DESCRIPTION
**Pull request by kecrily**

### CODE REVIEW

**Comment by nzakas** [comment]
Looks like this breaks the deploy. Can you take a look?

**Comment by kecrily** [comment]
I changed the sync command. The package.json in the root directory now comes entirely from `eslint/eslint/docs`, and syncing requires `cd scripys && npm i && npm run sync`

**Comment by nzakas** [comment]
We still need the deploy preview to work so we can verify the changes.

**Comment by kecrily** [comment]
Of course it is. Just need to make the deployment command a more complex one (which of course makes the dependencies will be exactly the same as upstream)

**Comment by kecrily** [comment]
I simplified it. Now it only requires

```sh
node scripts/install.js && npm run build
```

**Comment by nzakas** [comment]
@kecrily the deploy preview is still failing on this: 

```
9:45:01 PM: Build ready to start
9:45:07 PM: build-image version: d7b3dbfb0846505993c9a131894d1858074c90b4 (focal)
9:45:07 PM: build-image tag: v4.10.1
9:45:07 PM: buildbot version: 631f0363216079b7f038a5a332b842153439cb07
9:45:07 PM: Fetching cached dependencies
9:45:07 PM: Starting to download cache of 188.2MB
9:45:09 PM: Finished downloading cache in 1.486050276s
9:45:09 PM: Starting to extract cache
9:45:10 PM: Finished extracting cache in 1.890840465s
9:45:11 PM: Finished fetching cache in 3.455183841s
9:45:11 PM: Starting to prepare the repo for build
9:45:11 PM: Preparing Git Reference pull/52/head
9:45:11 PM: Parsing package.json dependencies
9:45:12 PM: Starting build script
9:45:12 PM: Installing dependencies
9:45:12 PM: Python version set to 2.7
9:45:12 PM: Started restoring cached node version
9:45:13 PM: Finished restoring cached node version
9:45:13 PM: v16.17.0 is already installed.
9:45:13 PM: Now using node v16.17.0 (npm v8.15.0)
9:45:13 PM: Started restoring cached build plugins
9:45:13 PM: Finished restoring cached build plugins
9:45:13 PM: Attempting ruby version 2.7.2, read from environment
9:45:14 PM: Using ruby version 2.7.2
9:45:14 PM: Using PHP version 8.0
9:45:14 PM: Started restoring cached go cache
9:45:14 PM: Finished restoring cached go cache
9:45:14 PM: Installing Go version 1.17 (requested 1.17)
9:45:18 PM: unset GOOS;
9:45:18 PM: unset GOARCH;
9:45:18 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.17.linux.amd64';
9:45:18 PM: export PATH="/opt/buildhome/.gimme/versions/go1.17.linux.amd64/bin:${PATH}";
9:45:18 PM: go version >&2;
9:45:18 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.17.linux.amd64.env"
9:45:18 PM: go version go1.17 linux/amd64
9:45:18 PM: Installing missing commands
9:45:18 PM: Verify run directory
9:45:19 PM: ​
9:45:19 PM: ────────────────────────────────────────────────────────────────
9:45:19 PM:   Netlify Build                                                 
9:45:19 PM: ────────────────────────────────────────────────────────────────
9:45:19 PM: ​
9:45:19 PM: ❯ Version
9:45:19 PM:   @netlify/build 27.18.2
9:45:19 PM: ​
9:45:19 PM: ❯ Flags
9:45:19 PM:   baseRelDir: true
9:45:19 PM:   buildId: 632a96cd607e730008e9b83a
9:45:19 PM:   deployId: 632a96cd607e730008e9b83c
9:45:19 PM: ​
9:45:19 PM: ❯ Current directory
9:45:19 PM:   /opt/build/repo
9:45:19 PM: ​
9:45:19 PM: ❯ Config file
9:45:19 PM:   No config file was defined: using default values.
9:45:19 PM: ​
9:45:19 PM: ❯ Context
9:45:19 PM:   deploy-preview
9:45:19 PM: ​
9:45:19 PM: ────────────────────────────────────────────────────────────────
9:45:19 PM:   1. Build command from Netlify app                             
9:45:19 PM: ────────────────────────────────────────────────────────────────
9:45:19 PM: ​
9:45:19 PM: $ npm run build
9:45:19 PM: npm ERR! code ENOENT
9:45:19 PM: npm ERR! syscall open
9:45:19 PM: npm ERR! path /opt/build/repo/package.json
9:45:19 PM: npm ERR! errno -2
9:45:19 PM: npm ERR! enoent ENOENT: no such file or directory, open '/opt/build/repo/package.json'
9:45:19 PM: npm ERR! enoent This is related to npm not being able to find a file.
9:45:19 PM: npm ERR! enoent
9:45:19 PM: npm ERR! A complete log of this run can be found in:
9:45:19 PM: npm ERR!     /opt/buildhome/.npm/_logs/2022-09-21T04_45_19_825Z-debug-0.log
9:45:19 PM: ​
9:45:19 PM: ────────────────────────────────────────────────────────────────
9:45:19 PM:   "build.command" failed                                        
9:45:19 PM: ────────────────────────────────────────────────────────────────
9:45:19 PM: ​
9:45:19 PM:   Error message
9:45:19 PM:   Command failed with exit code 254: npm run build (https://ntl.fyi/exit-code-254)
9:45:19 PM: ​
9:45:19 PM:   Error location
9:45:19 PM:   In Build command from Netlify app:
9:45:19 PM:   npm run build
9:45:19 PM: ​
9:45:19 PM:   Resolved config
9:45:19 PM:   build:
9:45:19 PM:     command: npm run build
9:45:19 PM:     commandOrigin: ui
9:45:19 PM:     environment:
9:45:19 PM:       - REVIEW_ID
9:45:19 PM:     publish: /opt/build/repo/_site
9:45:19 PM:     publishOrigin: ui
9:45:20 PM: Caching artifacts
9:45:20 PM: Started saving build plugins
9:45:20 PM: Finished saving build plugins
9:45:20 PM: Started saving pip cache
9:45:20 PM: Finished saving pip cache
9:45:20 PM: Started saving emacs cask dependencies
9:45:20 PM: Finished saving emacs cask dependencies
9:45:20 PM: Started saving maven dependencies
9:45:20 PM: Finished saving maven dependencies
9:45:20 PM: Started saving boot dependencies
9:45:20 PM: Finished saving boot dependencies
9:45:20 PM: Started saving rust rustup cache
9:45:20 PM: Finished saving rust rustup cache
9:45:20 PM: Started saving go dependencies
9:45:20 PM: Finished saving go dependencies
9:45:20 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
9:45:20 PM: Creating deploy upload records
9:45:20 PM: Failing build: Failed to build site
9:45:20 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
9:45:20 PM: Finished processing build request in 13.226688556s
```

**Comment by kecrily** [comment]
Let me create a netfily to test it out.

**Comment by kecrily** [comment]
https://63328cd527ae2f587d3bd011--soft-kulfi-0940ca.netlify.app/

I'm not having build issues, just css not loading, let me check.
截屏2022-09-27 13 44 15
截屏2022-09-27 13 45 42

**Comment by nzakas** [comment]
It looks like you’re running a script before `npm run build`. Can you create a Netlify.toml file to specify the correct build command to use?

**Comment by kecrily** [comment]
Yes, I am using [the command I wrote about here](https://github.com/eslint/zh-hans.docs.eslint.org/pull/52#issuecomment-1244412530). But now I have also created `netlify.toml`

**Review by nzakas — APPROVED** [review]

**Pull request merged**
